# Numpy 공부하기

# 0. 개요
- 메모리에 연속적인 공간에 데이터 저장
- 모든 요소가 같은 데이터 타입

# 1. 배열의 생성
(1) 리스트를 사용하여 narray생성<br>
(2) 튜플를 사용하여  narray생성<br>
(3) 함수를 사용하여 narray생성 (array, arange, asarry, ones, zeros 등)<br>



In [3]:
import numpy as np

### (1) 리스트를 사용하여 배열 생성

In [5]:
# 리스트를 사용하여 배열 생성

A = np.array([[3, 1, 9],
              [2, 5, 8],
              [4, 7, 6]])

A

array([[3, 1, 9],
       [2, 5, 8],
       [4, 7, 6]])

In [7]:
type(A)        # A의 데이터 타입 

numpy.ndarray

### (2) 튜플을 사용하여 배열 생성

In [6]:
# 튜플을 이용한 배열 생성

B = np.array([[3, 1, 9],
              [2, 5, 8],
              [4, 7, 6]])

B

array([[3, 1, 9],
       [2, 5, 8],
       [4, 7, 6]])

In [8]:
type(B)           # B의 데이터 타입 

numpy.ndarray

### (3) 함수를 사용하여 배열 생성

- #### zeros( )

In [11]:
C = np.zeros((2, 3))      # 모는 요소가 0인, 2행 3열의 배열(narray) 생성 (튜플로 크기지정)
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
type(C)

numpy.ndarray

- #### arange( )

In [13]:
D = np.arange(10, 20, 2)        # arange(start, end, step)  : start ~ end까지, step만큼씩 증가 (end값 포함 안됨)
D

array([10, 12, 14, 16, 18])

In [14]:
E = np.arange(0.1, 0.4, 0.1)     # 부동소수점 타입의 경우, 마지막값(0.4)가 포함되는 경우 발생
E

array([0.1, 0.2, 0.3, 0.4])

In [15]:
F = np.arange(1, 4, 1)
F

array([1, 2, 3])

- #### array( )

In [16]:
G = np.array([1, 2, 3], dtype='int')
G

array([1, 2, 3])

In [17]:
# dtype함수를 사용하여 데이터 타입지정 가능

dt = np.dtype('float')
H = np.array([1.1, 2.2, 3.3], dtype=dt)
H

array([1.1, 2.2, 3.3])

In [19]:
# 복소수 데이터 타입 지정
I = np.array([1.1+2.2j, 2.1-3.4j], dtype='cfloat')
I

array([1.1+2.2j, 2.1-3.4j])

# 2. 배열의 크기 (.shape)


### (1) 배열의 크기

In [20]:
arr = np.array([
    [1, 2, 3, 4],
    [-5, -6, -7, -8],
    [9, 10, 11, 12]
])

arr

array([[ 1,  2,  3,  4],
       [-5, -6, -7, -8],
       [ 9, 10, 11, 12]])

In [21]:
arr.shape     # 배열의 크기 

(3, 4)

### (2) 배열의 크기 변경

In [44]:
X = np.arange(12)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
X = np.arange(12).reshape(3,4)   
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 3. 배열의 속성 (.dtype)

In [22]:
arr.dtype

dtype('int64')

In [24]:
H.dtype

dtype('float64')

In [23]:
I.dtype

dtype('complex128')

# 4. 배열의 연산

In [27]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
],  dtype=np.float64)

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
],  dtype=np.float64)

arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [29]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [30]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [33]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [34]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [35]:
arr1**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [36]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

### 역행렬 계산
> linalg : 선형대수를 위한 모듈<br>
> inv(A) : 행렬A에 대한 역행렬

In [37]:
A = [[-2, 1], [1.5, -0.5]]

In [38]:
np.linalg.inv(A)       

array([[1., 2.],
       [3., 4.]])

### 행렬식
> det(A) : 행렬A의 행렬식 계산

In [39]:
np.linalg.det(A)

-0.5

### 행렬의 랭크
> matrix_rank(A)

In [40]:
np.linalg.matrix_rank(A)

2

### 벡터의 내적(Scalar product)
> inner(a, b) : 벡터a와 벡터b의 내적 계산

In [41]:
a, b = np.array([2, -4, 1]), np.array([3, 1, -2])
np.inner(a, b)

0

### 벡터의 외적(Cross product)
> cross(a, b) : 벡터a와 벡터b의 외적

In [42]:
np.cross(a, b)

array([ 7,  7, 14])

# 5. 배열의 인덱싱(indexing)

### (1) 1차원 배열 인덱싱

In [43]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]              # arr[n] : n번째 값 (0부터 시작)

5

In [47]:
arr[5:8]             # arr[m, n] : m ~ (n-1)번째 값 (5~7번째 값)

array([5, 6, 7])

In [49]:
arr[5:8] = 12        # 5 ~ 7번째 값을 12로 변경
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr[:5]

array([0, 1, 2, 3, 4])

In [51]:
arr[2:]

array([ 2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### (2) 2차원 배열 인덱싱
* arr[m, n]
> (m+1)행, (n+1)열
* arr[m, M:N]
> (m+1)행, (M+1)~N열
* arr[m:n, N]
> (m+1)~n행, N+1열
* arr[m:n, M:N]
> (m+1)~n행, (M+1)~N열

In [53]:
arr2d = np.array([
    [1, 2, 3, 4],         # 1행
    [5, 6, 7, 8],         # 2행
    [9, 10, 11, 12],      # 3행
    [13, 14, 15, 16]      # 4행
])

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
arr2d[2,1]    # (2+1)행, (1+1)열 : 3행 2열

10

In [55]:
arr2d[2, 1:3]   # 3행, (1+1)~3열 : 3행 2~3열

array([10, 11])

In [56]:
arr2d[1:3, 2]   # (1+1)~3행, 2+1열 : 2~3행, 3열

array([ 7, 11])

In [57]:
arr2d[1:3, :]   #

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr2d[:2, 1:3]   # 1~2행, 1~2열

array([[2, 3],
       [6, 7]])

In [59]:
arr2d[:2, 1:3] = 0
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
a = arr2d[1][1:]     # 2행, 2~마지막열까지
a

array([0, 0, 8])

### (3) boolean 인덱싱

In [77]:
import numpy as np

names = np.array(["Kang", "Pyo", "Hayoung", "Kang", "Hayoung", "Pyo", "Pyo"])
data = np.random.randn(7, 4)       # 난수로 된 7행 4열

In [78]:
names

array(['Kang', 'Pyo', 'Hayoung', 'Kang', 'Hayoung', 'Pyo', 'Pyo'],
      dtype='<U7')

In [79]:
data

array([[-1.05908487, -0.113958  ,  1.11521017,  0.27040135],
       [-0.44088945,  0.8138306 , -0.78152126,  1.80111508],
       [ 0.87928796, -0.83617978, -0.43609915, -0.22350434],
       [ 1.14600378, -0.14646746, -0.01346945,  0.61501945],
       [-1.08305562, -1.33431348,  0.79367061,  1.30043358],
       [-0.06586852, -1.12443747, -0.54142845,  1.66986857],
       [-1.41321119,  1.38113763, -1.37371733,  0.12919638]])

* 마스킹(masking)

In [80]:
names == "Kang"                                   # 마스크 (names에서 Kang이면 True)  : 1, 4번째

array([ True, False, False,  True, False, False, False])

In [81]:
data[names == "Kang", :]                          # data에서 1행과 4행의 모든 열 값

array([[-1.05908487, -0.113958  ,  1.11521017,  0.27040135],
       [ 1.14600378, -0.14646746, -0.01346945,  0.61501945]])

In [82]:
data[names == "Pyo", :]                           # data에서 Pyo에 해당하는 행의 값 출력 (2, 6, 7행)

array([[-0.44088945,  0.8138306 , -0.78152126,  1.80111508],
       [-0.06586852, -1.12443747, -0.54142845,  1.66986857],
       [-1.41321119,  1.38113763, -1.37371733,  0.12919638]])

In [83]:
data[(names == "Kang") | (names == "Pyo"), :]     # Kang 이거나, Pyo인 행만 출력 (즉, 1, 4행, 2, 6, 7행) = 1,2,4,6,7행

array([[-1.05908487, -0.113958  ,  1.11521017,  0.27040135],
       [-0.44088945,  0.8138306 , -0.78152126,  1.80111508],
       [ 1.14600378, -0.14646746, -0.01346945,  0.61501945],
       [-0.06586852, -1.12443747, -0.54142845,  1.66986857],
       [-1.41321119,  1.38113763, -1.37371733,  0.12919638]])

In [84]:
data[:, 3]                        # 모든 행의  4열의 모든 값

array([ 0.27040135,  1.80111508, -0.22350434,  0.61501945,  1.30043358,
        1.66986857,  0.12919638])

In [85]:
data[:, 3] < 0                    # 모든 행의 4열의 모든 값이, 0보다 작은 값이 있는 행을 True로 표시 ( 3, 5, 6행의 4열 값이 0보다 작음)

array([False, False,  True, False, False, False, False])

In [86]:
data[data[:, 3]<0, :]             # 4열 값이 0보다 작은 값이 있는 행의 모든 열의 값을 출력(즉, 3, 5, 6행의 모든 열값을 출력)

array([[ 0.87928796, -0.83617978, -0.43609915, -0.22350434]])

In [87]:
data[data[:, 3]<0, :]  = 0        # 4열 값이 0보다 작은 행의 모든열의 값을 0으로 설정 (즉, 3, 5, 6행의 값을 0으로 설정)

In [88]:
data

array([[-1.05908487, -0.113958  ,  1.11521017,  0.27040135],
       [-0.44088945,  0.8138306 , -0.78152126,  1.80111508],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.14600378, -0.14646746, -0.01346945,  0.61501945],
       [-1.08305562, -1.33431348,  0.79367061,  1.30043358],
       [-0.06586852, -1.12443747, -0.54142845,  1.66986857],
       [-1.41321119,  1.38113763, -1.37371733,  0.12919638]])

# 6. array관련 함수
* arange( )
* sqrt( )
* log10( )
* maximum( )
* minimum( )
* sum( )
* mean( )
* sort( )
* unique( )

### arange( ) 
> <h4>arange(n, m) : n, n+1, ... m-1</h4>

In [89]:
import numpy as np

arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### sqrt( )
> <h4>sqrt(arr) : array의 각 값에 대하여 "제곱근"을 출력</h4>

In [90]:
np.sqrt(arr)   # array의 각 값에 대하여 "제곱근"을 출력

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### log10( )
> <h4>log10(arr) : array의 각 값에 대하여 "로그" 출력</h4>

In [91]:
np.log10(arr)    # 로그

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

### 최대값, 최소값
> - <h4>maximum(x, y) : 배열a와 b의 각 위치에 있는 것들 중, 최대값 출력</h4>
> - <h4>minimum(x, y) : 배열a와 b의 각 위치에 있는 것들 중, 최소값 출력</h4>

In [92]:
x = np.random.randn(8)
y = np.random.randn(8)

In [93]:
x

array([ 0.44859995, -0.20819978, -0.86346819,  0.7294284 , -1.28884469,
        0.77927247, -1.16034621, -0.03328453])

In [94]:
y

array([ 1.68711745,  1.50068686, -0.73306991,  0.28530414,  0.27655345,
       -0.40142706, -1.13187373,  1.11196153])

In [95]:
np.maximum(x, y)   # 각 위치에 있는 것들 중, 최대값을 출력

array([ 1.68711745,  1.50068686, -0.73306991,  0.7294284 ,  0.27655345,
        0.77927247, -1.13187373,  1.11196153])

### sum( )
> d